#!/usr/bin/env bash
# Turnkey devnet bring-up: deploy → init_config → create_collection → smoke,
# then write the client env. One command, idempotent.
#
#   RPC_URL=https://<devnet rpc> ./scripts/deploy-devnet.sh
#
# The public api.devnet.solana.com throttles 504 KB program writes to failure.
# Use a real endpoint via RPC_URL:
#   Helius (free key):  https://devnet.helius-rpc.com/?api-key=YOUR_KEY
#   keyless fallback:   https://solana-devnet.api.onfinality.io/public
# SOL 3.1.x is required (4.0 panics on devnet getClusterNodes).
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
cd "$HERE"

RPC_URL="${RPC_URL:-https://solana-devnet.api.onfinality.io/public}"
WALLET="${WALLET:-$HOME/.config/solana/id.json}"
SOL_BIN="${SOL_BIN:-$HOME/.local/share/solana/install/releases/3.1.8/solana-release/bin/solana}"
PROGRAM_ID="2WtuXG6AX3erRp6eK5WiSTEEBec5zprQ7qLyLENfMQEH"

# Collection parameters (override via env). Devnet defaults are cheap and small.
export SPACES_TOTAL="${SPACES_TOTAL:-25}"
export SPACES_PRICE_SOL="${SPACES_PRICE_SOL:-0.25}"
export SPACES_ROYALTY_BPS="${SPACES_ROYALTY_BPS:-500}"
export SPACES_MAX_PER_WALLET="${SPACES_MAX_PER_WALLET:-0}"
export SPACES_TREASURY="${SPACES_TREASURY:-$($SOL_BIN-keygen pubkey "$WALLET")}"
export SPACES_BASE_URI="${SPACES_BASE_URI:-https://space.ekza.io/api/meta/}"
export SPACES_CLUSTER_LABEL="devnet"

echo "▸ cluster   devnet ($RPC_URL)"
echo "▸ wallet    $($SOL_BIN-keygen pubkey "$WALLET")"
echo "▸ program   $PROGRAM_ID"
echo "▸ params    total=$SPACES_TOTAL price=$SPACES_PRICE_SOL SOL royalty=${SPACES_ROYALTY_BPS}bps treasury=$SPACES_TREASURY"

echo "▸ [1/4] deploy"
if $SOL_BIN program show "$PROGRAM_ID" --url "$RPC_URL" >/dev/null 2>&1; then
  echo "  program already deployed — upgrading"
fi
# Resume from a saved buffer if BUFFER is set, else a fresh deploy.
DEPLOY_ARGS=(program deploy target/deploy/solana_ekza_space.so
  --program-id target/deploy/solana_ekza_space-keypair.json
  --url "$RPC_URL" --keypair "$WALLET" --use-rpc --max-sign-attempts 1000)
[ -n "${BUFFER:-}" ] && DEPLOY_ARGS+=(--buffer "$BUFFER")
$SOL_BIN "${DEPLOY_ARGS[@]}"

echo "▸ [2/4] bootstrap (init_config + create_collection)"
ANCHOR_PROVIDER_URL="$RPC_URL" ANCHOR_WALLET="$WALLET" \
  yarn --silent ts-node -P tsconfig.json scripts/bootstrap.ts

echo "▸ [3/4] smoke"
ANCHOR_PROVIDER_URL="$RPC_URL" ANCHOR_WALLET="$WALLET" \
  yarn --silent ts-node -P tsconfig.json scripts/smoke.ts

echo "▸ [4/4] client env"
COLLECTION=$(node -e "console.log(require('./deployments/devnet.json').collectionMint)")
CLIENT_ENV="../core/.env.devnet.local"
cat > "$CLIENT_ENV" <<ENV
# Generated by deploy-devnet.sh — point the client at the devnet program.
# Copy the values you need into core/.env.local, or run vite with this file.
VITE_SOLANA_NETWORK=devnet
VITE_SOLANA_RPC_URL_DEVNET=$RPC_URL
VITE_SPACE_PROGRAM_ID=$PROGRAM_ID
ENV
echo "  wrote $CLIENT_ENV"
echo
echo "✅ devnet ready. Program $PROGRAM_ID, collection $COLLECTION"
echo "   Test: cd ../core && cp .env.devnet.local .env.local && yarn dev  → open /mint (switch to Devnet)"
